//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTTDTEntities : DbContext
    {
        public CTTDTEntities()
            : base("name=CTTDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Science> Sciences { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Courses_BanMoTa> Courses_BanMoTa { get; set; }
        public virtual DbSet<Courses_ChuongTrinhDaoTao> Courses_ChuongTrinhDaoTao { get; set; }
        public virtual DbSet<Majors_BanMoTa> Majors_BanMoTa { get; set; }
        public virtual DbSet<Majors_ChuongTrinhDaoTao> Majors_ChuongTrinhDaoTao { get; set; }
        public virtual DbSet<Universities_BanMoTa> Universities_BanMoTa { get; set; }
        public virtual DbSet<Universities_ChuongTrinhDaoTao> Universities_ChuongTrinhDaoTao { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Robocon> Robocons { get; set; }
        public virtual DbSet<tbl_tuyensinh> tbl_tuyensinh { get; set; }
    }
}
