//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universities_BanMoTa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universities_BanMoTa()
        {
            this.Courses_BanMoTa = new HashSet<Courses_BanMoTa>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses_BanMoTa> Courses_BanMoTa { get; set; }
    }
}
